# Name of your site (displayed in the header)
name: "Ping5-1's blog"
# Short bio or description (displayed in the header)
description: "分享编程资源 | 学习路线 | 记录学习历程"

footer-links:
  email: wyp_hqu2017@163.com
  github: https://github.com/Ping5-1
# gitalk:

 url: https://ping5-1.github.io